name: rhizome_test
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - jupyter
  - cookiecutter
  - pandas==1.4.3
  - matplotlib
  - tensorflow
  - statsmodels==0.13.2
  - openpyxl
  - lightgbm==3.3.3
  - plotly
  - numpy==1.23.3
  - jupyter_contrib_nbextensions
  - black
  - isort
  - flake8
  - autoflake
  - pip:
    - PyYAML==6.0
    - setuptools==59.8.0
    - click==8.1.3
    - python-dotenv==0.21.0
    - -e . # setup.py